eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_ADDRESS:localhost}:8761/eureka
